### ISSUE TITLE
How can I access the "cut" files?

### ISSUE THREAD

**Issue by hhamamura** [danivelikova/cactuss#1]
Dear danivekikova.
I am hhamamura, a university student in Japan.
I saw your CACTUSS poster on MICCAI, became interested in your research, and ran the program on github.
However, I could not access the files in the submodule "cut" and could not run the program.
How can I access the "cut" files?

**Comment by danivelikova** [comment]
Hi @hhamamura,
Thank you for your interest in the project! The issue should be solved now, please rerun the code again.

**Comment by hhamamura** [comment]
The program ran fine.
Thank you very much.
